name: C/C++ CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
      - run: g++.exe -g ./Utils.cpp ./ContactController.cpp ./DisplayController.cpp ./main.cpp -lsqlite3 -o ./build/main
