name: C/C++ CI

on:
  push:
    branches: [ "master" ]


jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v3
    - name: Set up MinGW
    - uses: egor-tensin/setup-mingw@v2
    - name: Buid with gcc
      run: g++.exe -g ./Utils.cpp ./ContactController.cpp ./DisplayController.cpp ./main.cpp -lsqlite3 -o ./build/main
